"""Add expert_validations table

Revision ID: 106ec7f84f66
Revises: 15a2cedba113
Create Date: 2026-09-02 00:03:16.770587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '106ec7f84f66'
down_revision: Union[str, None] = '15a2cedba113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_validations',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('corrected_disease_id', sa.Integer(), nullable=True),
    sa.Column('corrected_pest_id', sa.Integer(), nullable=True),
    sa.Column('expert_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_disease_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['corrected_pest_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_reports.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_validations_diagnosis_id'), 'expert_validations', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_expert_validations_expert_id'), 'expert_validations', ['expert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_validations_expert_id'), table_name='expert_validations')
    op.drop_index(op.f('ix_expert_validations_diagnosis_id'), table_name='expert_validations')
    op.drop_table('expert_validations')
    # ### end Alembic commands ###
