"""Add KnowledgeBase table

Revision ID: 15a2cedba113
Revises: 78191afbdf58
Create Date: 2026-09-01 21:37:13.486842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '15a2cedba113'
down_revision: Union[str, None] = '78191afbdf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('DISEASE', 'PEST', name='issuecategory'), nullable=False),
    sa.Column('affected_crops', sa.String(length=500), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('trigger_conditions', sa.Text(), nullable=True),
    sa.Column('prevention_strategies', sa.Text(), nullable=True),
    sa.Column('treatment_recommendations', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_name'), 'knowledge_base', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_name'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
