"""Add monitoring_logs table

Revision ID: 728e5499ca89
Revises: b231976850c2
Create Date: 2026-09-02 00:21:25.991380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '728e5499ca89'
down_revision: Union[str, None] = 'b231976850c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_logs',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('health_status', sa.Enum('IMPROVING', 'NO_CHANGE', 'WORSENING', 'RESOLVED', name='healthstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_logs_diagnosis_id'), 'monitoring_logs', ['diagnosis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_logs_diagnosis_id'), table_name='monitoring_logs')
    op.drop_table('monitoring_logs')
    # ### end Alembic commands ###
