"""fix_cascade_delete_fks

Revision ID: 7874b775c6a4
Revises: 124fa67db634
Create Date: 2026-09-05 11:47:05.096222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '7874b775c6a4'
down_revision: Union[str, None] = '124fa67db634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expert_validations_diagnosis_id_fkey', 'expert_validations', type_='foreignkey')
    op.drop_constraint('expert_validations_expert_id_fkey', 'expert_validations', type_='foreignkey')
    op.create_foreign_key(None, 'expert_validations', 'diagnosis_reports', ['diagnosis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expert_validations', 'users', ['expert_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lab_referrals_expert_id_fkey', 'lab_referrals', type_='foreignkey')
    op.drop_constraint('lab_referrals_diagnosis_id_fkey', 'lab_referrals', type_='foreignkey')
    op.create_foreign_key(None, 'lab_referrals', 'users', ['expert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_referrals', 'diagnosis_reports', ['diagnosis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('monitoring_logs_diagnosis_id_fkey', 'monitoring_logs', type_='foreignkey')
    op.create_foreign_key(None, 'monitoring_logs', 'diagnosis_reports', ['diagnosis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'monitoring_logs', type_='foreignkey')
    op.create_foreign_key('monitoring_logs_diagnosis_id_fkey', 'monitoring_logs', 'diagnosis_reports', ['diagnosis_id'], ['id'])
    op.drop_constraint(None, 'lab_referrals', type_='foreignkey')
    op.drop_constraint(None, 'lab_referrals', type_='foreignkey')
    op.create_foreign_key('lab_referrals_diagnosis_id_fkey', 'lab_referrals', 'diagnosis_reports', ['diagnosis_id'], ['id'])
    op.create_foreign_key('lab_referrals_expert_id_fkey', 'lab_referrals', 'users', ['expert_id'], ['id'])
    op.drop_constraint(None, 'expert_validations', type_='foreignkey')
    op.drop_constraint(None, 'expert_validations', type_='foreignkey')
    op.create_foreign_key('expert_validations_expert_id_fkey', 'expert_validations', 'users', ['expert_id'], ['id'])
    op.create_foreign_key('expert_validations_diagnosis_id_fkey', 'expert_validations', 'diagnosis_reports', ['diagnosis_id'], ['id'])
    # ### end Alembic commands ###
