"""add_fcm_token_to_users

Revision ID: a4670db8df75
Revises: 7874b775c6a4
Create Date: 2026-09-24 16:14:15.933951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'a4670db8df75'
down_revision: Union[str, None] = '7874b775c6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoring_logs', 'expert_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.drop_constraint('fk_notifications_reference_id', 'notifications', type_='foreignkey')
    op.add_column('users', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.create_foreign_key('fk_notifications_reference_id', 'notifications', 'diagnosis_reports', ['reference_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.alter_column('monitoring_logs', 'expert_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
