"""Add lab_referrals table

Revision ID: b231976850c2
Revises: 106ec7f84f66
Create Date: 2026-09-02 00:16:06.812404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'b231976850c2'
down_revision: Union[str, None] = '106ec7f84f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_referrals',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(length=255), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'RECEIVED', 'ANALYZING', 'COMPLETED', 'CANCELLED', name='labreferralstatus'), nullable=False),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_reports.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_referrals_diagnosis_id'), 'lab_referrals', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_lab_referrals_expert_id'), 'lab_referrals', ['expert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_referrals_expert_id'), table_name='lab_referrals')
    op.drop_index(op.f('ix_lab_referrals_diagnosis_id'), table_name='lab_referrals')
    op.drop_table('lab_referrals')
    # ### end Alembic commands ###
